// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package plan

import (
	"backend/internal/product"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func NewControllerWire(db *gorm.DB) *Controller {
	repository := NewPlanRepository(db)
	productRepository := product.NewProductRepository(db)
	service := NewPlanService(repository, productRepository)
	controller := NewPlanController(service)
	return controller
}
