// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package analytics

import (
	"gorm.io/gorm"
)

// Injectors from wire.go:

func NewControllerWire(db *gorm.DB) *Controller {
	repository := NewRepository(db)
	service := NewService(repository)
	controller := NewController(service)
	return controller
}
