// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package product

import (
	"gorm.io/gorm"
)

// Injectors from wire.go:

func NewControllerWire(db *gorm.DB) *Controller {
	repository := NewProductRepository(db)
	service := NewProductService(repository)
	controller := NewProductController(service)
	return controller
}
