// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package tenant

import (
	"backend/internal/auth"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func NewControllerWire(db *gorm.DB) *Controller {
	repository := NewTenantRepository(db)
	userRepository := auth.NewUserRepository(db)
	service := NewTenantService(repository, userRepository)
	controller := NewTenantController(service)
	return controller
}
