// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	"backend/core"
	"backend/core/email"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func NewControllerWire(db *gorm.DB, cfg *core.Config) *Controller {
	userRepository := NewUserRepository(db)
	service := email.NewEmailService(cfg)
	authService := NewAuthService(userRepository, cfg, service)
	controller := NewAuthController(authService)
	return controller
}
